periodic = (None, 
('Hydrogen','H','NM', 'Hydr', 1), 
('Helium','He','NM', None, 0), 
('Lithium','Li','M', None, 1), 
('Beryllium','Be','M', None, 2), 
('Boron','B','SM', 'Bor', 0), 
('Carbon','C','NM', 'Carbon', 0), 
('Nitrogen','N','NM', 'Nitr', -3), 
('Oxygen','O','NM', 'Ox', -2), 
('Fluorine','F','NM', 'Fluor', -1), 
('Neon','Ne','NM', None, 0), 
('Sodium','Na','M', None, 1), 
('Magnesium','Mg','M', None, 2), 
('Aluminum','Al','M', None, 3), 
('Silicon','Si','SM', 'Silic', 0), 
('Phosphorus','P','NM', 'Phosph', -3), 
('Sulfur','S','NM', 'Sulf', -2), 
('Chlorine','Cl','NM', 'Clor', -1), 
('Argon','Ar','NM', None, 0), 
('Potassium','K','M', None, 1), 
('Calcium','Ca','M', None, 2), 
('Scandium','Sc','M', None, 3), 
('Titanium','Ti','M', None, 3), 
('Vanadium','V','M', None, 3), 
('Chromium','Cr','M', None, 2), 
('Manganese','Mn','M', None, 2), 
('Iron','Fe','M', None, 2), 
('Cobalt','Co','M', None, 2), 
('Nickel','Ni','M', None, 2), 
('Copper','Cu','M', None, 1), 
('Zinc','Zn','M', None, 2), 
('Gallium','Ga','M', None, 3),
('Germanium','Ge','SM', 'German', 4),
('Arsenic','As','SM', 'Arsen', -3),
('Selenium','Se','NM', 'Selen', -2),
('Bromine','Br','NM', 'Bro', -1),
('Krypton','Kr','NM', None, 0),
('Rubidium','Rb','M', None, 1),
('Strontium','Sr','M', None, 2),
('Yttrium','Y','M', None, 3),
('Zirconium','Zr','M', None, 4), 
('Niobium','Nb','M', None, 3),
('Molybdenum','Mo','M', None, 6),
('Technetium','Tc','M', None, 7),
('Ruthenium','Ru','M', None, 3),
('Rhodium','Rh','M', None, 3),
('Palladium','Pd','M', None, 2),
('Silver','Ag','M', None, 1),
('Cadmium','Cd','M', None, 2),
('Indium','In','M', None, 3),
('Tin','Sn','M', None, 2),
('Antimony','Sb','SM', 'Antimon', 3),
('Tellurium','Te','M', None, -2),
('Iodine','I','NM', 'Iod', -1),
('Xenon','xe','NM', None, 0),
('Cesium','Cs','M', None, 1),
('Barium','Ba','M', None, 2),
('Lanthanum','La','M', None, 3),
('Cerium','Ce','M', None),
('Praseodymium','Pr','M', None),
('Neodymium','Nd','M', None),
('Promethium','Pm','M', None),
('Samarium','Sm','M', None),
('Europium','Eu','M', None),
('Gadolinium','Gd','M', None),
('Terbium','Tb','SM', 'Terb'),
('Dysprosium','Dy','M', None),
('Holmium','Ho','M', None),
('Erbium','Er','M', None),
('Thulium','Tm','M', None),
('Ytterbium','Yb','M', None),
('Lutetium','Lu','M', None),
('Hafnium','Hf','M', None),
('Tantalum','Ta','M', None, 5),
('Tungsten','W','M', None, 6),
('Rhenium','Re','M', None, 7),
('Osmium','Os','M', None, 4),
('Iridium','Ir','M', None, 4),
('Platinum','Pt','M', None, 2),
('Gold','Au','M', None, 1),
('Mercury','Hg','M', None, 1),
('Thallium','Tl','M', None, 1),
('Lead','Pb','M', None, 2),
('Bismuth','Bi','M', None, 3),
('Polonium','Po','SM', 'Polon', 2),
('Astatine','At','M', None, -1),
('Radon','Rn','NM', None, 0),
('Francium','Fr','M', None, 1),
('Radium','Ra','M', None, 2),
('Actinium','Ac','M', None, 3),
('Thorium','Th','M', None),
('Protactinium','Pa','M', None),
('Uranium','U','M', None),
('Neptunium','Np','M', None),
('Plutonium','Pu','M', None),
('Americium','Am','M', None),
('Curium','Cm','M', None),
('Berkelium','Bk','M', None),
('Californium','Cf','M', None),
('Einsteinium','Es','M', None),
('Fermium','Fm','M', None),
('Mendelevium','Md','M', None),
('Nobelium','No','M', None),
('Lawrencium','Lr','M', None),
('Rutherfordium','Rf','M', None),
('Dubnium','Db','M', None),
('Seaborgium','Sg','M', None),
('Bohrium','Bh','M', None),
('Hassium','Hs','M', None),
('Meitnerium','Mt','M', None),
('Darmstadtium','Ds','M', None),
('Roentgenium','Rg','M', None),
('Copernicium','Cn','M', None),
('Nihonium','Nh','M', None),
('Flerovium','Fl','M', None),
('Moscovium','Mc','M', None),
('Livermorium','Lv','M', None),
('Tennessine','Ts','M', None),
('Oganesson','Og','M', None))
